### ISSUE TITLE
除了adobe四个字体之外的字体问题

### ISSUE THREAD

**Issue by lut777** [rioxwang/BUPTGraduateThesis#10]
我使用的是mac.
我在CSDN下载到了adobe的四种字体. 但是除此之外, 还需要单独安装simsun字体.
安装字体完毕后可不报错运行.
不清楚这种情况是否正常?
-- Update -----------------------------------------------
新一次make thesis的时候报错没有SimHei 字体.
正在处理中.
-- Update -----------------------------------------------
新bug. 没有Kaiti....有点崩溃了.
这是怎么回事啊.
-- Update -----------------------------------------------
Kaiti更新完毕. 
make thesis successful done! 
使用系统: MacOS 10.12.5  初始字库.

**Comment by rioxwang** [comment]
模板用的字体是WIN底下的那一套中文字体，所以MAC系统肯定要从WIN拷贝过去的哈

**Comment by qin-nz** [comment]
@rioxwang 如果没有版权问题，能不能在 make 的时候自动下载或者别的方式获取需要的字体呢？

**Comment by rioxwang** [comment]
这些字体都有版权的哦

**Comment by lut777** [comment]
确实是有版权, 但是实际上还是可以从windows获得的.....
不如 owner在给mac的使用栏目里增加一些可下载的地址呗~?

**Comment by rioxwang** [comment]
第一，我手上没有可下载的地址
第二，传播可下载地址也是不行的
第三，没记错的话，win的字体也有版权，虽然可以从windows拷贝，但windows系统本身就不是免费的
