### ISSUE TITLE
请问如何将页眉居中

### ISSUE THREAD

**Issue by mariolew** [rioxwang/BUPTGraduateThesis#11]
感觉学校的word模板中页眉是居中的，此模板中页眉并非居中，而是奇数页居右，偶数页居左

**Comment by rioxwang** [comment]
我毕业时学校的模板说明好像没有要求居中，是现在变了？

真要动的话，需要去修改buptgraduatethesis.cls的第635行和第645行，两边都加上\hfill就可以让内容居中了

**Comment by mariolew** [comment]
好的，多谢。
