### ISSUE TITLE
请问为何参考文献中的期刊都无法显示期刊名

### ISSUE THREAD

**Issue by mariolew** [rioxwang/BUPTGraduateThesis#14]
如题
@article{belhumeur2013localizing,
  title={Localizing parts of faces using a consensus of exemplars},
  author={Belhumeur, Peter N and Jacobs, David W and Kriegman, David J and Kumar, Neeraj},
  journal={IEEE transactions on pattern analysis and machine intelligence},
  volume={35},
  number={12},
  pages={2930--2940},
  year={2013},
  publisher={IEEE}
}

显示如下
[1] Belhumeur P N, Jacobs D W, Kriegman D J, et al. Localizing parts of faces using a consensus of
exemplars[J]. 2013, 35(12): 2930–2940.

求解 多谢

**Comment by qin-nz** [comment]
这可能和你的`bibliographystyle` 有关，请说下你用的是什么 style

**Comment by mariolew** [comment]
style就是buptgraduatethesis

**Comment by rioxwang** [comment]
可能是键值没有对应，建议参照bare_thesis.bib来写

具体说来：本模板中article提供的期刊名不是journal，是booktitle，当时是为了和其他类型相统一，共用函数减少代码量，所以没有和ieee相兼容

不过现在看来，很多用户都没有看说明，直接把自己的bib内容粘贴进去，所以目前有计划再改回去和ieee相兼容，不过什么时候实施还不一定，因为没有时间……

**Comment by mariolew** [comment]
@rioxwang 多谢啦，已解决。
