### ISSUE TITLE
如果将每一章后面的参考文献集中到整篇论文的最后

### ISSUE THREAD

**Issue by Lintong-common** [rioxwang/BUPTGraduateThesis#16]
\ifx\usechapbib\empty
\nocite{BSTcontrol}
\bibliographystyle{buptgraduatethesis}
\bibliography{bare_thesis}
\fi
将会在每一章后面单独生成这一章的参考文献
一个方法是将所有的篇章放到一个tex文件中，有没有保留每一章一个文件的方法

**Comment by qin-nz** [comment]
你可以使用 chapbib来进行切换，具体用法参见使用说明。
```
\documentclass[chapbib=false]{buptgraduatethesis}
```

**Comment by Lintong-common** [comment]
get it, thx!
