### ISSUE TITLE
请问目录如何设置缩进

### ISSUE THREAD

**Issue by mariolew** [rioxwang/BUPTGraduateThesis#17]
即不同级小节的缩进，目前是没有的

**Comment by mariolew** [comment]
已解决。

**Comment by qin-nz** [comment]
把解决方案说一下吧，给 @quietcoolwu 做参考。 #19

**Comment by quietcoolwu** [comment]
@mariolew 求解决方法。。。

**Comment by mariolew** [comment]
@quietcoolwu  在cls中搜\renewcommand*\l@section{\@dottedtocline，然后把从那行开始的三行中第二个括号中的0换成1.2、2和3.5

**Comment by quietcoolwu** [comment]
@mariolew 凹。。。这么明显的注释没看到， fixed， thx
