### ISSUE TITLE
论文目录的章节之间无缩进?

### ISSUE THREAD

**Issue by quietcoolwu** [rioxwang/BUPTGraduateThesis#19]
@rioxwang @baggiorio18 
您好, 我使用 makethesis 编译时, 发现 section 和 subsection 之间的层次在论文目录中没有缩进, 如图
请问这该如何解决?
![screenshot from 2017-11-23 23-52-24](https://user-images.githubusercontent.com/11589421/33180936-6252da6c-d0a9-11e7-9a2e-42c2f804a291.png)
使用的是 TexLive 2017@Linux

**Comment by qin-nz** [comment]
并没有要求要有缩进吧……

**Comment by Lintong-common** [comment]
目录没缩进应该没问题吧

**Comment by quietcoolwu** [comment]
@rioxwang fixed, sorry

**Comment by librahu** [comment]
请问是怎么解决的@quietcoolwu
