### ISSUE TITLE
Mac下没有Sim*字体

### ISSUE THREAD

**Issue by hu6360567** [rioxwang/BUPTGraduateThesis#2]
我已经安装过MacTex 2015，Office 2016 for mac，但是在运行编译脚本时，还是会提示SimSun等字体找不到。
在Mac的字体册中也找不到相对应的Sim*字体。

是否要修改xeCJK-fonts.def中相关配置到ST*字体？

**Comment by rioxwang** [comment]
中易宋体是Windows提供的，不是OFFICE提供的哦，两个方法解决：

第一种，把WINDOWS下的Sim*字体考到MAC下，用字体册安装一下

第二种，字体配置文件修改一下，改用ST华文宋体系列

看喜好，不过第二种要小心，华文系列和中易系列还是可以看得出不小区别的，尤其是标点符号，不要因为字体原因不被接受

**Comment by hu6360567** [comment]
好的，多谢。

另外，我没有看到任何使用Adobe Kaiti/Fangsong的地方？这两个字体是在哪里使用的呢？

Adobe字体所使用的地方只有首页封面对吗？

**Comment by rioxwang** [comment]
有点久了，记得不是很清楚了，应该是只在封面用了

**Comment by hu6360567** [comment]
好的，多谢。
