### ISSUE TITLE
请问如何将缩略语表放在论文前面？

### ISSUE THREAD

**Issue by quietcoolwu** [rioxwang/BUPTGraduateThesis#21]
@rioxwang RT,最好和表格公式索引等放在一起, thx

**Comment by rioxwang** [comment]
你好，打算下一个版本更新的时候开放一个选项出来，让大家选放前还是放后，不过现在比较忙，结合前面的一堆待改进的东西，可能没那么快放出来

学校那边似乎并没有要求缩略语的位置，所以不是很紧迫的话，不妨先将就着用

**Comment by quietcoolwu** [comment]
@rioxwang 嗯嗯，谢谢您的热心回答!有空时研究下看看能不能提个pr
