### ISSUE TITLE
中文标题的中英文字体问题

### ISSUE THREAD

**Issue by qin-nz** [rioxwang/BUPTGraduateThesis#23]
首先，我的中文题目中含有了一个英文单词。
在中文标题中，可以看到定义的是\hei，但实际显示中，中文看起来是黑体的，但英文就不是了，这个如何解决？

**Comment by qin-nz** [comment]
临时解决方案：
```
\ctitle{{\setmainfont{SimHei} 中文标题Hello}}
```

**Comment by rioxwang** [comment]
你好！

摘要中的标题设置，一直是按照中文黑体，西文Times New Roman来设置的，哪怕是中西文混排的情况。

原因是SimHei并不适合拿来设置西文，如果一定要非衬线也是改成Arial，不过因为英文摘要要求是Times New Roman，所以这里仍然用Times New Roman。

所以如果实在想去改动，那可以用你找到的那个方法，不过建议不要用SimHei，用Arial会美观些。

**Comment by qin-nz** [comment]
@rioxwang 非常感谢。
