### ISSUE TITLE
请问论文主标题的合理换行如何实现

### ISSUE THREAD

**Issue by quietcoolwu** [rioxwang/BUPTGraduateThesis#25]
@rioxwang @baggiorio18 
RT，由于论文标题字数不多不少，导致换行时效果比较尴尬，如图：
![screenshot from 2017-12-19 13-11-44](https://user-images.githubusercontent.com/11589421/34141750-3e6f1a74-e4be-11e7-8b3a-5b88d2ce8953.png)

好像添加 `\\\\` 这样也不行，请问应该在哪里设置？

**Comment by qin-nz** [comment]
使用 \mbox 就可以的。  
`\mbox{面向一二三四的一二三四五六} \mbox{研究}`
注意两个\mbox之间必须有空格

**Comment by qin-nz** [comment]
不过，两个mbox中间使用空格会让摘要页显示的时候多出一个空格……
可以考虑使用零长度空格来解决。

**Comment by quietcoolwu** [comment]
@qin-nz solved THX!

**Comment by qin-nz** [comment]
@quietcoolwu 在pdf说明文档中也有提示：

> 可以使用\titlebreak 命令手动控制论文题目换行的位置，目前暂不支持三行的论文题目。
