### ISSUE TITLE
盲审版的独创性声明和授权声明

### ISSUE THREAD

**Issue by qin-nz** [rioxwang/BUPTGraduateThesis#29]
对于被抽中盲审的学生，学校要求上传时需保留独创性声明和授权声明，且无需签字；
但是在全员都需要上传的最终论文中，要求应删除“独创性声明”、“关于论文使用授权的说明”及论文致谢部分。

![image](https://user-images.githubusercontent.com/6998071/34825041-e3828a1e-f70b-11e7-83cd-c7a101e0a4b2.png)
---
![image](https://user-images.githubusercontent.com/6998071/37497728-35a9f730-28f5-11e8-85f6-939d43007768.png)

**Comment by qin-nz** [comment]
关于这个矛盾的要求，我已经向研究生院反映了，但愿能够得到答复

**Comment by ihewro** [comment]
对于被抽中盲审的学生，学校要求上传时需保留独创性声明和授权声明，且无需签字；
这个是从哪个文件中呢，没有找到相关文件

---
在教务网的答辩信息申请的说明里面有这个盲审的材料说明，也就是图二
