### ISSUE TITLE
makethesis.bat install 缺少13docstrip.tex 

### ISSUE THREAD

**Issue by quantumen** [rioxwang/BUPTGraduateThesis#33]
按照说明文档buptgraduatethesis.pdf安装最新的包之后， 我在windows系统下的cmd里面输入makethesis.bat install 来安装，发现安装不下去，缺少一个13docstrip.tex文件。我的电脑安装的是2016年的CTeX 2.9.2.164。 想请教是否哪里安装的有问题呢？？

**Comment by qin-nz** [comment]
你的 CTeX 2.9.2.164 安装的时候是 minium 还是 full ？
如果是minium的话，重装以便full版。
