### ISSUE TITLE
Version 7.1 版本下使用样例example无法编译成功

### ISSUE THREAD

**Issue by shuoyuan** [rioxwang/BUPTGraduateThesis#35]
**安装项目版本：** 
Version 7.1；commitID: c51aae6c9b78a0515214e298c2a894f7d820a81a；
**状况：**
安装(`./makethesis install`)之后，将example中的文件复制到项目根目录(`mv ./example/* ./`)之后编译(`./makethesis thesis`)报错；
![image](https://user-images.githubusercontent.com/25116465/45748062-3a7a0380-bc3a-11e8-87f0-b37bc8fd2be5.png)

**ps：**
相同环境下，回滚14个commit，即回滚到(commitID: 54a01f89d8dedf69261cc1df1e4ae2456a91f5b2)重新安装，可以编译成功。

**Comment by qin-nz** [comment]
@shuoyuan 稍后我会尝试复现一下这个问题。

**Comment by qin-nz** [comment]
@shouyuan 请提供一下你的编译环境（系统、tex版本）和运行的命令，我在macOS和、Windows上没问题。另外，请确认工作空间干净（`git status`）

**Comment by elysion122** [comment]
您好，我遇到完全相同的问题，我用的是windows7系统，texlive2018，编译成功后，将example的内容复制到根目录下，在cmd中运行 makethesis.bat thesis。

**Comment by qin-nz** [comment]
@elysion122 @shuoyuan 了解，我会尽快修复的。

**Comment by qin-nz** [comment]
@shuoyuan 我看了一下，你说的没错，这确实是我的失误。你可以尝试着提交 pull request 来修复这个问题。

> 我发现line 2311的\end{center}是否缺失了\begin{center} ?

**Comment by c04s316** [comment]
> @shuoyuan我看了一下，你说的没错，这确实是我的失误。你可以尝试着提交拉请求来修复这个问题。
> 
> > 我发现line 2311的\ end {center}是否缺失了\ begin {center}？

V7.1 ， 不是少一个 \begin{center}，而是多一个 \end {center}。
buptgraduatethesis.cls  ， line 971 ,注释掉 \end {center}，就行了。

**Comment by shuoyuan** [comment]
> > @shuoyuan我看了一下，你说的没错，这确实是我的失误。你可以尝试着提交拉请求来修复这个问题。
> > > 我发现line 2311的\ end {center}是否缺失了\ begin {center}？
> 
> V7.1 ， 不是少一个 \begin{center}，而是多一个 \end {center}。
> buptgraduatethesis.cls ， line 971 ,注释掉 \end {center}，就行了。

nice！的确是多了一个\end{center}.  
在新克隆下的V7.1代码库下，`./makethesis install`之后，打开buptgraduatethesis.cls，注释掉line 971的`\end {center}`，再`./makethesis thesis`，编译成功。

ps: 不过我回滚到v7.0了，论文已经写太多了，不想折腾了。。
