### ISSUE TITLE
mac下编译时候没有KaiTi

### ISSUE THREAD

**Issue by librahu** [rioxwang/BUPTGraduateThesis#37]
install的时候没有问题， 编译出现如下错误
The font "KaiTi" cannot be found.
是怎么回事呢
望解答

**Comment by qin-nz** [comment]
看 https://github.com/rioxwang/BUPTGraduateThesis/blob/master/README.md
![image](https://user-images.githubusercontent.com/6998071/49052116-7e364e00-f225-11e8-8933-f3fb395f8437.png)

**Comment by librahu** [comment]
@qin-nz 这四个字体都已经安装了，不过 xeCJK-fonts.def文件里的这句话还是找不到字体
![image](https://user-images.githubusercontent.com/11657264/49053303-98bef600-f22a-11e8-9c18-54005c8db68a.png)
我把他改成下面这样就可以运行，不知道有没有问题。
![image](https://user-images.githubusercontent.com/11657264/49053377-dcb1fb00-f22a-11e8-9fd8-905f1cc1beeb.png)

**Comment by qin-nz** [comment]
应该可以的，不过最好还是自己装一个正常的楷体字体吧

**Comment by qin-nz** [comment]
试试这个？ https://fontzone.net/download/kaiti

**Comment by librahu** [comment]
@qin-nz 非常感谢

**Comment by qin-nz** [comment]
@librahu 看起来这个问题你已经解决了，那我就关闭issue了。
