### ISSUE TITLE
参考文献分别附在各章之后时，最后多出现一个有编号的空条目，咋回事儿呢？

### ISSUE THREAD

**Issue by colin-fox** [rioxwang/BUPTGraduateThesis#5]
在bare_thesis.tex中设置chapbib=true，同时在makethesis编译脚本中修BIBTYPE="chapbib"，编译完成后发现当参考文献分别附在各章之后时，最后总会多出现一个有编号的空条目, 例如：参考文献中总共有30个正常引用的条目，编译后总会多出一个  "[31]."，咋回事儿呢？　

测试手动编译并且保留中间文件，打开各章的.bbl文件，发现除了正常引用的条目外，最后总会多出一个条目：

\bibitem{BSTcontrol}
.

不知是不是这个惹的祸：（

**Comment by rioxwang** [comment]
你好！
首先，BSTcontrol是用于控制参考文献条目显示方式的，例如作者显示数量等，跟这个应该没关系。
其次，我这里也没办法重现你所说的症状，用GitHub下载未修改的来编译，分章参考文献是正常的。
建议你也试试用未修改的来编译看看。我猜测，比较可能是你的bib文件书写有误，有时候多一个句号逗号都会导致这样的问题。

**Comment by qin-nz** [comment]
@colin-fox 我先关闭问题了，如果问题还存在，请重新打开问题。
