### ISSUE TITLE
【教务检查反馈】封面需更新

### ISSUE THREAD

**Issue by buptchan** [rioxwang/BUPTGraduateThesis#50]
2019/06/02   下午去教务检查论文，信通院研究生教务科老师反馈，首页的“专业领域”在今年的版本中应该换为“专业”。
需将buptgraduatethesis.cfg第65行  
\def\bupt@label@cmajor{专业领域}
替换为
 \def\bupt@label@cmajor{专\hspace{2em}业}

同时反馈“论文使用授权的说明”也需要更新，但目前这一版也能通过教务审核。需要删除最后一句“本学位论文不属于保密范围，适用本授权书。”
请参考以上进行更新

**Comment by qin-nz** [comment]
@buptchan 你已经列举出来了，我相信你可以用 pull request 来改的
