### ISSUE TITLE
Windows中的字体

### ISSUE THREAD

**Issue by BUPT-YY** [rioxwang/BUPTGraduateThesis#52]
Win10, 
基本环境TeXlive2019:下载自https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/Images/
texlive2019-20190410.iso
IDE用的是TeXStudio. http://texstudio.sourceforge.net/
请问，如何安装您这个模板。。。为啥模板还需要安装。。

还有, windows里为啥也找不到Adobe Kaiti Std、Adobe Song Std等字体

**Comment by qin-nz** [comment]
请看 README
