### ISSUE TITLE
引用如何取消上标的形式

### ISSUE THREAD

**Issue by Ethan730** [rioxwang/BUPTGraduateThesis#55]
如题 编译后默认\cite是上标 删掉cls文件里natbib的super也不行 希望能由 研究[1]中xxx这种方式 不知道怎么改  救救孩子

**Comment by Ethan730** [comment]
发现example里有。。是我瞎了

**Comment by together00** [comment]
不知道您是否指得是 `\onlinecite`？根据原文，我们可以猜测 `\onlinecite` 是针对网站类型的引用，而并非您所指的那样，尽管它能实现类似的效果。因此，我认为这个问题是没有解决的。
