### ISSUE TITLE
bugs on bare_thesis.bib

### ISSUE THREAD

**Issue by xuzhenqi** [rioxwang/BUPTGraduateThesis#6]
bare_thesis.bib 12--15行：

```
@BUPTGraduateThesisBSTCTL{BSTcontrol,
  CTLmaxnum_authors = "3"
  CTLswitch_chs_punc = "no",
}
```

这个逗号的位置应该放到上一行去吧。

```
@BUPTGraduateThesisBSTCTL{BSTcontrol,
  CTLmaxnum_authors = "3",
  CTLswitch_chs_punc = "no"
}
```

很奇怪，example里编译没有出错，但是我编译自己的论文的时候，就会出现引用找不到的问题。

**Comment by rioxwang** [comment]
是的，这个逗号的位置错了，还真没注意到，这两周刚好在弄一个新的功能，整好了一起更新

至于你说的引用找不到的问题，是否可以详细描述一下？

**Comment by xuzhenqi** [comment]
结果不太好复现。编译出来的pdf里\ref和\cite都是问号。我是通过手动执行bibtex后才发现错误提示的。另外，建议把编译的log保存下来，脚本里许多log给扔掉了。

**Comment by rioxwang** [comment]
你好，编译的log除了屏幕上显示的之外，编译系统默认还会有一份存储在bare_thesis.log中，可以在里面查询。如果想在屏幕上看，可以把编译脚本里的输出重定向（>nul或者>/dev/null）去掉。

实际上并不是所有的输出都重定向了，第一遍用xelatex编译的就没有做重定向，因为一般来说只要是正文里的错误，第一遍编译就过不去会在这里体现，全部保留的话信息量反而过多。不过如果是参考文献的问题，确实是需要再去掉参考文献那里的重定向，或者去看log文件。

另外，如果能够重现问题，可以随时与我联系，谢谢！

**Comment by colin-fox** [comment]
我也遇到，按照这个法子修改问题解决！

**Comment by qin-nz** [comment]
这个问你已经修复了。
