### ISSUE TITLE
脚注编号超过11时，脚注编号无法显示

### ISSUE THREAD

**Issue by imaginezz** [rioxwang/BUPTGraduateThesis#61]
Latex代码：
```latex
脚注测试1\footnote[1]{我是第一个脚注}。

脚注测试2\footnote[10]{我是第十个脚注}。

脚注测试3\footnote[11]{我是第十一个脚注}
```
编译后的效果：
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/10754732/73135258-078c1f00-407b-11ea-9cd4-5ee1fa4b7fb3.png">

**Comment by imaginezz** [comment]
查明原因是模板中使用的字体不支持超过10的序号。可以设置每页重置编号解决。

**Comment by loganwhite** [comment]
另一个解决方案是使用`\textcircled{}`，具体做法是将buptgraduatethesis.cls文件的第239至248行注释，删除250行相应个数个`\fi`（10个）。同时为更好的显示，`\textcircled{}`中字号建议使用`\tiny`而不是`\qihao`。

**Comment by Jhy1993** [comment]
> 查明原因是模板中使用的字体不支持超过10的序号。可以设置每页重置编号解决。

怎么每页重置编号呀

**Comment by Jhy1993** [comment]
只要在preamble里加上：
\usepackage[perpage]{footmisc}
