### ISSUE TITLE
引用学位论文的格式是什么？

### ISSUE THREAD

**Issue by AdmiralDollBug** [rioxwang/BUPTGraduateThesis#63]
示例的bib文件里面有：
* BOOK
* ARTICLE
* PROCEEDINGS
* INPROCEEDINGS
* DISSERTATION
* TECHREPORT
* PATENT
* STANDARD
* NEWSPAPER
* ELECTRONIC
等格式，但没有学位论文的引用格式。常规的BIBTEX格式不起作用。
请问应该如何解决？

**Comment by xinleiyu** [comment]
DISSERTATION 这个是就是指学位论文，thesis的另一种说法

**Comment by AdmiralDollBug** [comment]
> DISSERTATION 这个是就是指学位论文，thesis的另一种说法

已知晓，感谢
