### ISSUE TITLE
运行makethesis.bat install遇到以下问题 I can't find file "install //buptgraduatethesis.ins"

### ISSUE THREAD

**Issue by karlsruhe20** [rioxwang/BUPTGraduateThesis#65]
![issue](https://user-images.githubusercontent.com/54131863/75047842-7afe4080-5502-11ea-8392-9399723eaaf2.png)

**Comment by xinleiyu** [comment]
注意执行`makethesis.bat`的目录下应当包含完整项目文件，你在目录`C:\Windows\system32`下执行命令肯定找不到项目文件.......包括上一个Issue #64，都应当是CMD使用方面的

**Comment by karlsruhe20** [comment]
> 注意执行`makethesis.bat`的目录下应当包含完整项目文件，你在目录`C:\Windows\system32`下执行命令肯定找不到项目文件.......包括上一个Issue #64，都应当是CMD使用方面的

应该是cmd使用的问题，在摸索中，，，
