### ISSUE TITLE
参考文献首页无页眉

### ISSUE THREAD

**Issue by Ethan730** [rioxwang/BUPTGraduateThesis#67]
求解决方案 没有找到参考文献相关的 headings或者plain的设置的地方

**Comment by xinleiyu** [comment]
`buptgraduatethesis.cls` 文件中把这里的plain改成headings，但是这样摘要、目录、表格索引、插图索引、符号对照表、参考文献、致谢都有页眉了。
这里之前本来就是headings的，不知道哪个版本改成了plain。我不知道再改回来是不是对的哈，请确认一下。

```
\def\@schapter#1{%
  \cleardoublepage\phantomsection%
  \thispagestyle{bupt@plain}%plain改成headings
  \global\@topnum\z@%
  \@afterindenttrue%
  \ifx\bupt@preschapter\empty
    \relax
  \else
    \bupt@preschapter
  \fi
  \@makeschapterhead{#1}
  \@afterheading}

```

**Comment by Ethan730** [comment]
> `buptgraduatethesis.cls` 文件中把这里的plain改成headings，但是这样摘要、目录、表格索引、插图索引、符号对照表、参考文献、致谢都有页眉了。
> 这里之前本来就是headings的，不知道哪个版本改成了plain。我不知道再改回来是不是对的哈，请确认一下。
> 
> ```
> \def\@schapter#1{%
>   \cleardoublepage\phantomsection%
>   \thispagestyle{bupt@plain}%plain改成headings
>   \global\@topnum\z@%
>   \@afterindenttrue%
>   \ifx\bupt@preschapter\empty
>     \relax
>   \else
>     \bupt@preschapter
>   \fi
>   \@makeschapterhead{#1}
>   \@afterheading}
> ```

感觉这样好像也不太行 我现在是生成后手动添加的 谢谢啦 打算最近学一学latex

**Comment by xinleiyu** [comment]
我看了一下，是从2018年3月份的 #27 更改了删除所有的这些页眉。
但是为啥要删除这个页眉，不知道有没有根据？
如果没有要求的话，其实把这个恢复了就好 @qin-nz

**Comment by qin-nz** [comment]
@Ethan730

**Comment by qin-nz** [comment]
@Ethan730 直接 Revert 这个 commit 应该就可以。当时删除是为了和 Word 保持一致，这个应该是没有明确要求的。如果能找到个依据应该添加页眉的话，我很乐意恢复。
https://github.com/rioxwang/BUPTGraduateThesis/pull/27/commits/4a53ab45d2ac7ca7771db7459eb1894a5d4e519b

**Comment by xinleiyu** [comment]
@qin-nz  谢谢解惑。从我从知网下载到的论文看，好像其实挺不一致的，而且找不着啥依据。这个只在不分章节参考文献时候出一点点问题

**Comment by Ethan730** [comment]
@qin-nz 谢谢 因为实验室祖传word模板问题有 怕被自己老师怼 没有强制要求
