### ISSUE TITLE
报告：按照Change Logs v6.2修改后， enumerate环境序号有问题。

### ISSUE THREAD

**Issue by colin-fox** [rioxwang/BUPTGraduateThesis#7]
报告的现象：多个enumerate的item之间进行了连续编号。现在暂时可在每个enumerate环境里对计数器重新置零进行解决，不知是否属于可重现的问题，谨慎报告哈:-）

\begin{enumerate}**\setcounter{enumi}{0}**
    \item ...
    \item ...
\end{enumerate}

**Comment by rioxwang** [comment]
恩？这个有点怪，之前也没注意到，我明天测试一下
谢谢！

**Comment by rioxwang** [comment]
很奇怪，我测试后没有重现该问题
我把ch_intro.tex第19、23、27和31行的itemize变为enumerate，两处都是从1开始计数
你是不是用到其它的宏包产生相互影响了？

**Comment by colin-fox** [comment]
嗯，我用的包较多，应该我自己出问题的概率大一些:)
