### ISSUE TITLE
封面题目换行报错

### ISSUE THREAD

**Issue by NigelBoxing** [rioxwang/BUPTGraduateThesis#75]
论文题目很长，封面一行放不下，自动换行显示的样子：、
```text
我这里是一个很长的题目一行装
不下
```
但是以前被老师纠正过不要拆分词语，所以理想的题目样式：
```text
我这里是一个很长的题目一行
装不下
```
填写题目的代码在metadata.tex的第20行
```tex
\ctitle{我这里是一个很长的题目一行装不下}
```
如果我使用"\\\\"换行，texstudio编译会报错：`Something's wrong--perhaps a missing \item. \makefrontmatter`，
如果使用"\newline"换行，texstudio编译会报错：`Undefined control sequence. \makefrontmatter`

**Comment by qin-nz** [comment]
你好，你说的问题确实存在，不妨试试把你的题目修改成这样，加个空格，或者用特殊命令加一些空白字符之类的。
`我这里是一个很长的题目一行   装不下`

**Comment by NigelBoxing** [comment]
> 你好，你说的问题确实存在，不妨试试把你的题目修改成这样，加个空格，或者用特殊命令加一些空白字符之类的。
> `我这里是一个很长的题目一行 装不下`

好的，谢谢，我试了试您的方法，\hspace{2em}可以，但\qquad好像就不行，但不重要了。
我刚刚翻了翻dtx文件，可以通过\titlebreak手动换行，方法是
```tex
\ctitle{我这里是一个很长的题目一行\titlebreak{装不下}}
```
`\titlebreak`**目前暂不支持三行的论文题目**
