### ISSUE TITLE
报告：设置保密级别后（非公开级别），编译有误。

### ISSUE THREAD

**Issue by colin-fox** [rioxwang/BUPTGraduateThesis#8]
根据编译报错信息反向经查找，问题追溯到buptgraduatethesis.cfg的**\def\bupt@authorization@title{关于论文使用授权的说明}**  
定义中的最后一行：
**本学位论文属于保密在\bupt@meta@classdur解密后适用本授权书。**
报错是无法读出**\bupt@meta@classdur**的值。

咱们学校基本都是公开密级的，编译没任何问题，只是在修改其他密级后编译的时候遇到了，多一嘴报告一下，属于低重要级别的issue，呵呵 :-)

**Comment by rioxwang** [comment]
已修正，漏了个空格，谢谢啦！下周放在新版一起放出来。

PS：看来没有涉密人员用过本模板：P

**Comment by qin-nz** [comment]
fixed by 13b6a9c0c28fa02e163828b999ca3f162f388df7
