### ISSUE TITLE
首页错位如何解决

### ISSUE THREAD

**Issue by smartmark-pro** [rioxwang/BUPTGraduateThesis#84]
如图
![image](https://user-images.githubusercontent.com/28584805/112612952-838a1e80-8e5a-11eb-91e0-5195d384cd8c.png)

**Comment by smartmark-pro** [comment]
似乎是自己导了一个奇怪的包,  去掉了, 就正常了

**Comment by qin-nz** [comment]
@smartmark-pro 把你导入的包也写一下，后面如果有人遇到也可以做参考

**Comment by smartmark-pro** [comment]
好像是一个ctex的包， 是因为我还不熟悉导致的。首页格式应该是geography包控制， 如果修改它也可能会导致类似情况
