### ISSUE TITLE
引用类型的问题

### ISSUE THREAD

**Issue by wangyifantech** [rioxwang/BUPTGraduateThesis#9]
Hi，模板很好用，但是遇到一个小问题，好像不支持博士论文的引用呢？@PHDTHESIS的类型显示不出来？不知道是不是只支持模板中给出的文献类型？

**Comment by rioxwang** [comment]
只支持模板中给出的文献类型哈，不过模板中有个dissertation类型的参考文献，是为硕博士学位论文准备的，你可以用这个

**Comment by emosfet** [comment]
好的，我已经找到了，谢谢啦，在模板pdf中好像没有引用这个类型的文档，我再bib文件里翻到的。
